version: "3.8"

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - shared-volume:/output

  runner:
    build:
      context: .
      dockerfile: Dockerfile.run
    depends_on:
      - builder
    volumes:
      - ./monarca_iadb_org.marcos.crt:/certs/client.pem
      - ./monarca_iadb_org.marcos.key:/certs/client_key.pem
      - shared-volume:/debs/:ro 
    extra_hosts:
      - "ironbridgeapi.com:51.11.137.80"

volumes:
  shared-volume:
